# Generated by Django 3.2.3 on 2021-05-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_id', models.CharField(max_length=200)),
                ('tw_screen', models.CharField(max_length=50)),
                ('tw_account_created_at', models.DateTimeField(verbose_name='date user created')),
                ('follower', models.BooleanField(verbose_name='False for main account, True for follower')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_tw_id', models.CharField(max_length=200)),
                ('following_position', models.IntegerField()),
                ('tw_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetcore.twusers')),
            ],
        ),
    ]
