# Generated by Django 3.2.3 on 2021-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twusers',
            name='name',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='twusers',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Is account protected or private'),
        ),
        migrations.AddField(
            model_name='twusers',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Is account verified'),
        ),
    ]
