# Generated by Django 3.2.3 on 2021-05-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcore', '0002_auto_20210516_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twusers',
            name='follower',
        ),
    ]
