# Generated by Django 3.2.3 on 2021-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcore', '0005_auto_20210519_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaFollowers',
        ),
    ]
