# Generated by Django 3.2.3 on 2021-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcore', '0006_delete_metafollowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='tw_user',
        ),
        migrations.AddField(
            model_name='followers',
            name='tw_id',
            field=models.CharField(default='-111', max_length=200),
        ),
    ]
