# Generated by Django 3.2.3 on 2021-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcore', '0007_auto_20210528_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_id', models.CharField(default='-111', max_length=200)),
            ],
        ),
    ]
