# Generated by Django 3.2.3 on 2021-05-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetcore', '0008_tempusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUsers',
        ),
    ]
